#app:
#  resource: "@AppBundle/Controller/"
#  type:     annotation


links:
  pattern:  /links
  defaults: { _controller: AppBundle:Link:link}

resume:
  pattern:  /resume
  defaults: { _controller: AppBundle:Resume:resume}

pages:
  pattern:  /{page}
  defaults: { _controller: AppBundle:Default:index, page: "home" }
