
tim_doerzbacher_links:
  pattern:  /links
  defaults: { _controller: TimDoerzbacherBundle:Link:link}

tim_doerzbacher_resume:
  pattern:  /resume
  defaults: { _controller: TimDoerzbacherBundle:Resume:resume}
  
tim_doerzbacher_pages:
  pattern:  /{page}
  defaults: { _controller: TimDoerzbacherBundle:Default:index, page: "home" }
