parameters:
#    tim_doerzbacher.example.class: timmd909\Bundle\Example

services:
#    tim_doerzbacher.example:
#        class: %tim_doerzbacher.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
